services:

  user_db:
    image: mysql
    container_name: user_db
    ports:
      - 3301:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    networks:
      - venkatmurthy

  eurekaserver:
    image: "venkatmurthy2204/salon-eureka:v1"
    ports:
      - 8070:8070
    healthcheck:
      test: ["CMD-SHELL","curl --fail --silent eurekaserver:8070/actuator/health/readiness | grep UP || exist 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: eurekaserver

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - venkatmurthy

  user:
    image: "venkatmurthy2204/salon-user:v1"
    ports:
      - 8081:8081
    healthcheck:
      test:  "curl --fail --silent user:8081/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: user
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "userservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://user_db:3306/user_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - venkatmurthy


networks:
  venkatmurthy:
    driver: "bridge"



